### ISSUE TITLE
SSR Support

### ISSUE THREAD

**Issue by Emiliano-Bucci** [duskload/react-device-detect#24] opened 2019-04-25 15:29 UTC
Hi! I saw a closed issue that was about implementing SSR detection: is there any updates on this? Thanks! :)

**Comment by duskload** [comment] 2019-05-29 15:00
Hi @Emiliano-Bucci, thanks for your report! It's been a while, since I've planned to add support for SSR to library but I don't have time for this now. I will try to add it in the future.

I would gladly accept PR if you have thoughts on this.

**Comment by duskload** [comment] 2019-09-03 09:06
Duplicate of #21.

**Closed by duskload** 2019-09-03 09:06 UTC
